name: plugspot
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen:
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.6
  geolocator: ^9.0.2
  lite_rolling_switch: ^1.0.1
  qr_code_scanner: ^1.0.1
  permission_handler: ^10.2.0
  flutter_stripe: ^9.2.0
  http: ^0.13.6
  fluttertoast: ^8.2.1
  url_launcher: ^6.1.11
  flutter_inappwebview: ^5.7.2+3
  image_picker: ^0.8.7+5
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  cookie_jar: ^4.0.2
  http_parser: ^4.0.2
  intl: ^0.18.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  
  uses-material-design: true
  assets:
    - images/
    - images/icon/

 